//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVIenHUIT_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPM
    {
        public string MAPM { get; set; }
        public string MASACH { get; set; }
        public Nullable<int> SLMUON { get; set; }
        public Nullable<decimal> TIENTHECHAN { get; set; }
    
        public virtual QLSACH QLSACH { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
