//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVIenHUIT_13.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPM_DATABASE_THUVIENEntities1 : DbContext
    {
        public CNPM_DATABASE_THUVIENEntities1()
            : base("name=CNPM_DATABASE_THUVIENEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIASACH> BIASACH { get; set; }
        public virtual DbSet<CHITIETPM> CHITIETPM { get; set; }
        public virtual DbSet<DOCGIA> DOCGIA { get; set; }
        public virtual DbSet<NHAXUATBAN> NHAXUATBAN { get; set; }
        public virtual DbSet<PHIEU_MUONPHONG> PHIEU_MUONPHONG { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUON { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRA { get; set; }
        public virtual DbSet<PHONGHOP> PHONGHOP { get; set; }
        public virtual DbSet<QLNHANVIEN> QLNHANVIEN { get; set; }
        public virtual DbSet<QLSACH> QLSACH { get; set; }
        public virtual DbSet<ROLE_USER> ROLE_USER { get; set; }
        public virtual DbSet<TACGIA> TACGIA { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THELOAI> THELOAI { get; set; }
        public virtual DbSet<THETHUVIEN> THETHUVIEN { get; set; }
    }
}
