//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVIenHUIT_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_MUONPHONG
    {
        public string MAPHIEU { get; set; }
        public string MATHE { get; set; }
        public string MAPH { get; set; }
        public Nullable<System.DateTime> NGAYMUON { get; set; }
        public Nullable<System.TimeSpan> GIOMUON { get; set; }
        public Nullable<int> SL_NGUOITHAMGIA { get; set; }
        public string MUCDICH { get; set; }
        public Nullable<decimal> TIENPHAT { get; set; }
        public Nullable<System.TimeSpan> GIOTRA { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        public string GHICHU_NV { get; set; }
    
        public virtual THETHUVIEN THETHUVIEN { get; set; }
        public virtual PHONGHOP PHONGHOP { get; set; }
        public int TRANGTHAI { get; internal set; }
    }
}
