
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PHIEUTRA
{

    public string MAPT { get; set; }

    public string MAPM { get; set; }

    public string MANV { get; set; }

    public Nullable<System.DateTime> NGAYTRA { get; set; }

    public Nullable<decimal> TONG_TIENTHECHAN { get; set; }

    public Nullable<decimal> TIENPHAT { get; set; }



    public virtual QLNHANVIEN QLNHANVIEN { get; set; }

    public virtual PHIEUMUON PHIEUMUON { get; set; }

}

}
