//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVIenHUIT_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGHOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGHOP()
        {
            this.PHIEU_MUONPHONG = new HashSet<PHIEU_MUONPHONG>();
        }
    
        public string MAPHONG { get; set; }
        public string VITRI { get; set; }
        public Nullable<int> SL_NGUOITOIDA { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_MUONPHONG> PHIEU_MUONPHONG { get; set; }
    }
}
