
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class QLNHANVIEN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QLNHANVIEN()
    {

        this.PHIEUTRAs = new HashSet<PHIEUTRA>();

        this.PHIEUMUONs = new HashSet<PHIEUMUON>();

        this.PHIEU_MUONPHONG = new HashSet<PHIEU_MUONPHONG>();

    }


    public string MANV { get; set; }

    public string TENNV { get; set; }

    public Nullable<System.DateTime> NGSINH { get; set; }

    public string CHUCVU { get; set; }

    public string SDIENTHOAI { get; set; }

    public string MAIL { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEU_MUONPHONG> PHIEU_MUONPHONG { get; set; }

}

}
