
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class QLSACH
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QLSACH()
    {

        this.CHITIETPMs = new HashSet<CHITIETPM>();

    }


    public string MASACH { get; set; }

    public string TENSACH { get; set; }

    public string MATG { get; set; }

    public string MATHELOAI { get; set; }

    public string MAXB { get; set; }

    public Nullable<int> NAMXB { get; set; }

    public Nullable<int> SL { get; set; }

    public Nullable<int> TINHTRANG { get; set; }

    public string MOTA { get; set; }



    public virtual BIASACH BIASACH { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIETPM> CHITIETPMs { get; set; }

    public virtual NHAXUATBAN NHAXUATBAN { get; set; }

    public virtual TACGIA TACGIA { get; set; }

    public virtual THELOAI THELOAI { get; set; }

}

}
