
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TACGIA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TACGIA()
    {

        this.QLSACHes = new HashSet<QLSACH>();

    }


    public string MATG { get; set; }

    public string TENTG { get; set; }

    public Nullable<System.DateTime> NGAYSINH { get; set; }

    public string QUOCTICH { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QLSACH> QLSACHes { get; set; }

}

}
