
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TAIKHOAN
{

    public string USERNAME { get; set; }

    public byte[] PASS { get; set; }

    public Nullable<int> ROLE_ID { get; set; }



    public virtual ROLE_USER ROLE_USER { get; set; }

}

}
