
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class THAMSO
{

    public string TENTHAMSO { get; set; }

    public Nullable<int> GIATRI { get; set; }

    public string MOTA { get; set; }

}

}
