//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThuVIenHUIT_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETHUVIEN
    {
        public string MATHE { get; set; }
        public string MADG { get; set; }
        public Nullable<System.DateTime> NGAYCAP { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
