
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class THETHUVIEN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public THETHUVIEN()
    {

        this.PHIEU_MUONPHONG = new HashSet<PHIEU_MUONPHONG>();

        this.PHIEUMUONs = new HashSet<PHIEUMUON>();

    }


    public string MATHE { get; set; }

    public string MADG { get; set; }

    public Nullable<System.DateTime> NGAYCAP { get; set; }

    public Nullable<System.DateTime> NGAYHETHAN { get; set; }

    public string TRANGTHAI { get; set; }



    public virtual DOCGIA DOCGIA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEU_MUONPHONG> PHIEU_MUONPHONG { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }

}

}
