
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TINTUC1
{

    public int MaTin { get; set; }

    public string TieuDe { get; set; }

    public string MoTaNgan { get; set; }

    public string HinhAnh { get; set; }

    public Nullable<System.DateTime> NgayDang { get; set; }

    public Nullable<int> LoaiTin { get; set; }

    public Nullable<bool> HienThi { get; set; }

    public string Link { get; set; }

}

}
