
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QL_ThuVIenHUIT_13.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VIPHAM
{

    public int MAVP { get; set; }

    public string MAPM { get; set; }

    public string MASACH { get; set; }

    public string HINHTHUCVP { get; set; }

    public string CHITIETVP { get; set; }

    public Nullable<decimal> SOTIENPHAT { get; set; }

    public Nullable<System.DateTime> NGAYGHINHAN { get; set; }



    public virtual PHIEUMUON PHIEUMUON { get; set; }

}

}
